name: Hourly News Update and Deploy

on:
  schedule:
    # Runs every 5 minutes (Adjusted for reliability)
    - cron: "*/5 * * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow workflow to commit back to the repo
      pages: write # Required for GitHub Pages deployment action
      id-token: write # Required for GitHub Pages deployment action

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Ensure matches your requirements

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Main Script
        env:
          # Pass secrets securely as environment variables
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
          CAMB_AI_API_KEY: ${{ secrets.CAMB_AI_API_KEY }}
          # Pass other secrets
          YOUR_WEBSITE_NAME: ${{ secrets.YOUR_WEBSITE_NAME }}
          YOUR_WEBSITE_LOGO_URL: ${{ secrets.YOUR_WEBSITE_LOGO_URL }}
          MAX_HOME_PAGE_ARTICLES: ${{ secrets.MAX_HOME_PAGE_ARTICLES }}
          MAX_LATEST_NEWS: ${{ secrets.MAX_LATEST_NEWS }}
          CHECK_INTERVAL_SECONDS: ${{ secrets.CHECK_INTERVAL_SECONDS }}
          YOUR_SITE_BASE_URL: ${{ secrets.YOUR_SITE_BASE_URL || vars.YOUR_SITE_BASE_URL || '' }}
        run: python src/main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # --- CORRECTED: Only add specific output dirs/files expected to change ---
          git add public/ data/processed_json/ data/processed_article_ids.txt
          # Optionally add the log file ONLY if it exists
          if [ -f "dacoola.log" ]; then git add dacola.log; fi
          # -----------------------------------------------------------------------

          # Check if there are staged changes
          if git diff --staged --quiet; then
            echo "No content changes to commit."
          else
            echo "Content changes detected. Committing..."
            git commit -m "Automated hourly news update [skip ci]"
            # Retry push logic...
            retry_count=0
            max_retries=3
            until git push origin ${{ github.ref_name }} || [ $retry_count -eq $max_retries ]; do
              retry_count=$((retry_count+1))
              echo "Push failed. Retrying (${retry_count}/${max_retries})..."
              sleep 5
            done
            if [ $retry_count -eq $max_retries ]; then
              echo "Push failed after $max_retries attempts."
              exit 1
            fi
            echo "Changes pushed successfully."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- DEPLOYMENT STEP ---
      # Option 1: Deploy to GitHub Pages is ACTIVE

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public # Upload the public directory content

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Other options remain commented out...
      # Option 2: Deploy via rsync/scp
      # - name: Deploy to Server via rsync ...
      # Option 3: Deploy using Netlify CLI
      # - name: Deploy to Netlify ...
      # Option 4: Deploy using Vercel CLI
      # - name: Install Vercel CLI ...
