name: Update Site Content Hourly

on:
  schedule:
    # Runs every hour at the beginning of the hour
    - cron: "0 * * * *"
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Or your desired version

      - name: Install dependencies
        run: pip install -r requirements

      - name: Run update script
        run: python src/main.py
        env: # Add ALL required environment variables here from GitHub Secrets
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
          CAMB_AI_API_KEY: ${{ secrets.CAMB_AI_API_KEY }} # Optional, only if you use it
          YOUR_WEBSITE_NAME: ${{ secrets.YOUR_WEBSITE_NAME }}
          YOUR_WEBSITE_LOGO_URL: ${{ secrets.YOUR_WEBSITE_LOGO_URL }}
          MAX_HOME_PAGE_ARTICLES: ${{ secrets.MAX_HOME_PAGE_ARTICLES }}
          MAX_LATEST_NEWS: ${{ secrets.MAX_LATEST_NEWS }}
          # Add any other env vars your script needs

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@users.noreply.github.com'
          # Add data folder if it changes (e.g., processed IDs)
          git add public data
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated content update [skip ci]"
            git push
          fi
